# Generated by Django 5.2.1 on 2026-09-17 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_account_status_user_deleted_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='cgu_accepted',
            field=models.BooleanField(default=False, verbose_name='CGU acceptées'),
        ),
        migrations.AddField(
            model_name='user',
            name='onboarding_completed',
            field=models.BooleanField(default=False, verbose_name="Parcours d'onboarding terminé"),
        ),
    ]
