# Generated by Django 5.2.1 on 2026-03-02 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_order_total_amount_alter_orderitem_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_confirmed_by_vendor',
            field=models.BooleanField(default=False, verbose_name='Arrivée confirmée par le vendeur'),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_rating',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Note de livraison (1-5)'),
        ),
        migrations.AddField(
            model_name='order',
            name='estimated_minutes',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Temps de livraison estimé (minutes)'),
        ),
        migrations.AddField(
            model_name='order',
            name='package_photo',
            field=models.ImageField(blank=True, null=True, upload_to='orders/packages/%Y/%m/%d/', verbose_name='Photo du colis'),
        ),
        migrations.AddField(
            model_name='order',
            name='vendor_lat',
            field=models.FloatField(blank=True, null=True, verbose_name='Latitude livreur'),
        ),
        migrations.AddField(
            model_name='order',
            name='vendor_lng',
            field=models.FloatField(blank=True, null=True, verbose_name='Longitude livreur'),
        ),
        migrations.AddField(
            model_name='order',
            name='vendor_location_updated',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Dernière mise à jour GPS livreur'),
        ),
    ]
